import type { MetadataRoute } from "next";

// Next.js serves this as /robots.txt at runtime.
// We allow the whole site — no private areas, no staging routes.
// The sitemap lives at /sitemap.xml (generated by src/app/sitemap.ts).
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },
    sitemap: "https://rauhut.com/sitemap.xml",
    host: "https://rauhut.com",
  };
}
