import type { MetadataRoute } from "next";

// Next.js serves this as /robots.txt at runtime.
// We allow the whole site — no private areas, no staging routes — except
// /designs (see disallow below).
// The sitemap lives at /sitemap.xml (generated by src/app/sitemap.ts).
//
// P7 (2026-09-12, Founder brief): Disallow: /designs added on top of the
// existing X-Robots-Tag: noindex, nofollow header (next.config.ts,
// designsNoIndexHeaders) and the now-fixed noindex,nofollow meta tag
// (src/app/designs/page.tsx). This is a deliberate change of an earlier
// documented decision, not an oversight — next.config.ts explains at
// length why Disallow was originally left OUT: it stops the crawler from
// fetching the page at all, so it never sees the noindex signal, and a
// URL can still get indexed bare (no snippet) via external backlinks
// while Disallowed. That risk is why this Disallow was verified rather
// than added on request alone: a search for `site:rauhut.com/designs`
// returned zero results just before this change (2026-09-12) — nothing
// is indexed yet, so there is no existing entry for Disallow to freeze.
// If /designs is ever linked externally again, this trade-off needs a
// fresh look before trusting Disallow alone.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: "/designs",
    },
    sitemap: "https://rauhut.com/sitemap.xml",
    host: "https://rauhut.com",
  };
}
